language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="ocp-browser:. ocp-index:."
  - DISTRO="debian-stable"
  matrix:
  - OCAML_VERSION="4.02"
  - OCAML_VERSION="4.03"
  - OCAML_VERSION="4.04"
  - OCAML_VERSION="4.05"
  - OCAML_VERSION="4.06"
  - OCAML_VERSION="4.07"
  - OCAML_VERSION="4.08"
  - OCAML_VERSION="4.09"
  - OCAML_VERSION="4.10"
  - OCAML_VERSION="4.11"
  - OCAML_VERSION="4.12"
